"""Deterministic historical replay, backtesting and walk-forward validation (Phase 11).

Replays the durable Phase 4 observation record through the *existing* Phase 5-10 pipeline, in
canonical market order, and records what the frozen contracts would have decided and what those
decisions would have produced.

**One brain.** There is no feature formula, no regime rule, no strategy, no rank score and no
outcome rule in this package. It constructs the same ``MarketEngine`` the live process runs,
hands it historical events and a market clock, and reports the result. A disagreement between
live and replay on identical canonical events would be a bug, not a difference of opinion.

**Offline.** Nothing here imports, names or could reach an execution manager, an order executor,
a broker control, an arm state or a live session limit, and tests assert it. Replay results are
research: they are persisted under the run's own namespace, and no code in this application
reads one back to change a decision.

**Research only.** A threshold a fold discovers is an observation about recorded history. Phase
11 ships no way to apply one — no endpoint, no button, no consumer — and ``ReplayEvidence`` is
written for a Phase 12 that does not exist yet.
"""

from quant_engine.replay.clock import (
    AVAILABILITY_LAG_MS,
    WARMUP_BARS,
    ReplayClock,
    settlement_tail_ms,
    slowest_timeframe,
    warmup_duration_ms,
)
from quant_engine.replay.engine import (
    OUTSIDE_EVALUATION_WINDOW,
    REPLAY_NAMESPACE,
    SESSION_GUARD_BLOCKED,
    ReplayEngine,
    ReplayProgress,
    ReplayResult,
    ReplayStorage,
    ReplayWindow,
    WindowedPaperEngine,
    derive_window,
    replay_run_id,
    settings_fingerprint,
)
from quant_engine.replay.models import (
    MIN_SELECTION_SAMPLE,
    REPLAY_VERSION,
    SUPPORTED_ANALYTICS_VERSION,
    SUPPORTED_FEATURE_VERSION,
    SUPPORTED_PAPER_VERSION,
    SUPPORTED_RANKING_VERSION,
    SUPPORTED_REGIME_VERSION,
    SUPPORTED_STRATEGY_VERSION,
    WARNING_CODES,
    ContributionRow,
    DailyDistribution,
    DailyPerformance,
    EquityPoint,
    FoldMetrics,
    LatencyScenario,
    OutcomeTally,
    PayoutScenario,
    ReplayCausalityAudit,
    ReplayCoverage,
    ReplayDatasetSummary,
    ReplayDiagnostics,
    ReplayEntryLayer,
    ReplayEvidence,
    ReplayManifest,
    ReplayRun,
    ReplayRunStatus,
    ReplaySourceFilter,
    ReplaySourceMode,
    ReplaySourceType,
    ReplaySummary,
    RollingWindow,
    SessionGuardDay,
    SessionGuardScenarioReport,
    WalkForwardFold,
    WalkForwardSettings,
    WalkForwardSummary,
)
from quant_engine.replay.report import build_evidence, build_summary, guard_report, latency_report
from quant_engine.replay.repository import list_runs, replay_root, run_dir
from quant_engine.replay.robustness import (
    contributions,
    coverage,
    daily,
    drawdown,
    equity,
    latency_scenario,
    payout_scenarios,
    rolling,
    streaks,
    tally,
    warnings_for,
)
from quant_engine.replay.service import (
    ReplayBusy,
    ReplayJob,
    ReplayReport,
    ReplayService,
    default_source,
    execute,
)
from quant_engine.replay.source import (
    REPLAY_ENTRY_LAYER,
    InMemoryObservationSource,
    ParquetObservationSource,
    ReplayEvent,
    ReplaySource,
    event_digest,
    market_time_of,
    ordering_key,
    replay_provenance,
)
from quant_engine.replay.walk_forward import (
    FoldWindow,
    analyse,
    embargo_for,
    plan_count,
    plan_duration,
    run_fold,
    select,
)

__all__ = [
    "AVAILABILITY_LAG_MS",
    "MIN_SELECTION_SAMPLE",
    "OUTSIDE_EVALUATION_WINDOW",
    "REPLAY_ENTRY_LAYER",
    "REPLAY_NAMESPACE",
    "REPLAY_VERSION",
    "SESSION_GUARD_BLOCKED",
    "SUPPORTED_ANALYTICS_VERSION",
    "SUPPORTED_FEATURE_VERSION",
    "SUPPORTED_PAPER_VERSION",
    "SUPPORTED_RANKING_VERSION",
    "SUPPORTED_REGIME_VERSION",
    "SUPPORTED_STRATEGY_VERSION",
    "WARMUP_BARS",
    "WARNING_CODES",
    "ContributionRow",
    "DailyDistribution",
    "DailyPerformance",
    "EquityPoint",
    "FoldMetrics",
    "FoldWindow",
    "InMemoryObservationSource",
    "LatencyScenario",
    "OutcomeTally",
    "ParquetObservationSource",
    "PayoutScenario",
    "ReplayBusy",
    "ReplayCausalityAudit",
    "ReplayClock",
    "ReplayCoverage",
    "ReplayDatasetSummary",
    "ReplayDiagnostics",
    "ReplayEngine",
    "ReplayEntryLayer",
    "ReplayEvent",
    "ReplayEvidence",
    "ReplayJob",
    "ReplayManifest",
    "ReplayProgress",
    "ReplayReport",
    "ReplayResult",
    "ReplayRun",
    "ReplayRunStatus",
    "ReplayService",
    "ReplaySource",
    "ReplaySourceFilter",
    "ReplaySourceMode",
    "ReplaySourceType",
    "ReplayStorage",
    "ReplaySummary",
    "ReplayWindow",
    "RollingWindow",
    "SessionGuardDay",
    "SessionGuardScenarioReport",
    "WalkForwardFold",
    "WalkForwardSettings",
    "WalkForwardSummary",
    "WindowedPaperEngine",
    "analyse",
    "build_evidence",
    "build_summary",
    "contributions",
    "coverage",
    "daily",
    "default_source",
    "derive_window",
    "drawdown",
    "embargo_for",
    "equity",
    "event_digest",
    "execute",
    "guard_report",
    "latency_report",
    "latency_scenario",
    "list_runs",
    "market_time_of",
    "ordering_key",
    "payout_scenarios",
    "plan_count",
    "plan_duration",
    "replay_provenance",
    "replay_root",
    "replay_run_id",
    "rolling",
    "run_dir",
    "run_fold",
    "select",
    "settings_fingerprint",
    "settlement_tail_ms",
    "slowest_timeframe",
    "streaks",
    "tally",
    "warmup_duration_ms",
    "warnings_for",
]
